### ISSUE TITLE
Unable to preventDefault inside passive event listener due to target being treated as passive.

### ISSUE THREAD

**Issue by bdthemes** [ivmello/easeScroll#3]
**Unable to preventDefault inside passive event listener due to target being treated as passive.**

Showing this error from Chrome v.73 

I think here the problem: `void e.preventDefault())` line 74

**Comment by duealab** [comment]
line 252

L && K && (u("mousedown", a, {passive: false}), u("mousewheel", n, {passive: false}), u("load", t, {passive: false}))

add {passive:false}

**Comment by bdthemes** [comment]
Thanks @duealab it worked 😊

**Comment by buraksahin59** [comment]
> line 252
> 
> L && K && (u("mousedown", a, {passive: false}), u("mousewheel", n, {passive: false}), u("load", t, {passive: false}))
> 
> add {passive:false}

Thank you :))
